name:                matsubara0507-ghpages
version:             0.3.0.0
homepage:            https://matsubara0507.github.io
license:             MIT
author:              MATSUBARA Nobutada
category:            Web
ghc-options:
  - -Wall
  - -threaded
dependencies:
  - base == 4.*
  - extensible
  - lens

executables:
  site:
    source-dirs: app
    main: site.hs
    ghc-options:
      - -threaded
    dependencies:
      - blaze-html
      - containers
      - filepath
      - hakyll
      - mtl
      - skylighting
      - time
      - yaml

tests:
  check-links:
    main: test/check-links/Main.hs
    dependencies:
      - http-client
      - http-client-tls
      - http-types
      - hspec
      - scalpel-core
      - shelly
      - text
