name:                matsubara0507-ghpages
version:             0.2.0.1
homepage:            https://matsubara0507.github.io
license:             MIT
author:              MATSUBARA Nobutada
category:            Web
ghc-options:
  - -Wall
  - -threaded
dependencies:
  - base == 4.*

executables:
  site:
    main: site.hs
    ghc-options:
      - -threaded
    dependencies:
      - containers
      - hakyll
      - skylighting
      - yaml

tests:
  check-links:
    main: test/check-links/Main.hs
    dependencies:
      - http-client
      - http-client-tls
      - http-types
      - hspec
      - scalpel-core
      - shelly
      - text
