resolver: lts-13.11

packages:
- '.'

extra-deps:
- extensible-0.6.1
- membership-0
- hakyll-4.12.5.2
- lrucache-1.2.0.1
# - Cabal-2.2.0.1
# - containers-0.5.11.0
# - barbies-1.1.3.0
# - binary-0.8.7.0
# - text-1.2.4.0
# - pandoc-citeproc-0.13.0.1
# - git: https://github.com/matsubara0507/extensible-instances.git
#   commit: 8dabe7a3dd9cf162e2d81e4ca16dbe73b98a3809

flags: {}

extra-package-dbs: []
