resolver: lts-10.5

packages:
- '.'

extra-deps:
- hakyll-4.11.0.0
- pandoc-citeproc-0.13.0.1
- git: https://github.com/matsubara0507/extensible-instances.git
  commit: 8dabe7a3dd9cf162e2d81e4ca16dbe73b98a3809

flags: {}

extra-package-dbs: []
